// 醫美診所。時間變回來了，錢也變多了。其他的東西還在盤點。
export const AESTHETIC_EVENTS = [
  {
    id: 'ae_consult_upsell',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 3,
    text: '諮詢師把報價單推到你面前：「醫師，這位客人預算三十萬，我幫她排了全臉。你等一下進去就說『妳的中臉需要支撐』。」',
    choices: [
      {
        label: '照著講。',
        effects: { money: 12, self: -4 },
        log: '你講了。她簽了單，離開時很開心。你回到診間才發現，剛剛那個語氣，跟你當年跟家屬解釋病情時一模一樣。',
      },
      {
        label: '只做她真的需要的。',
        effects: { money: -5, self: 4 },
        log: '那張單子從三十萬變成六萬。諮詢師在門外嘆了口氣。月底業績會議上這件事會被提出來，用的字是「醫師配合度」。',
      },
    ],
  },
  {
    id: 'ae_kpi',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 3,
    text: '月會。白板上是每位醫師的業績排名，你的名字在下面數來第二個。院長說：「我們不是要逼大家，只是讓大家知道自己的位置。」',
    effects: { self: -4 },
    log: '散會後有人把白板拍下來傳到群組，配了一個哭臉。沒有人回。',
  },
  {
    id: 'ae_livestream',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    once: true,
    weight: 2,
    text: '你的第一場直播。行銷交代：前三分鐘不要講醫學，先講故事。留言區有人問你單身嗎，有人問會不會痛，沒有人問成分。',
    effects: { money: 20, self: -3 },
    log: '兩小時，賣掉四十組療程。你想起以前在晨會報 case，講三十分鐘，台下五個人有四個在滑手機。',
  },
  {
    id: 'ae_price_war',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 3,
    text: '對街新開的診所打出「肉毒一單位九元」。你算過成本，那個價格連原廠藥都買不起。',
    choices: [
      {
        label: '跟進降價。',
        effects: { money: -25, self: -3 },
        log: '你也貼了促銷海報。三個月後對街又降了一次。這條街上沒有人賺到錢，只有客人學會了等下一波。',
      },
      {
        label: '不跟。守住你用的藥。',
        effects: { money: -40, self: 3 },
        log: '來客數掉了三成。有客人在櫃檯直接問：「別家比較便宜，你們憑什麼？」你解釋了原廠和水貨的差別，她說：「打起來還不是一樣。」',
      },
    ],
  },
  {
    id: 'ae_equipment_loan',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 3,
    text: '儀器商說這台新機器「別家都有了」，五年分期，一個月十八萬。你問一年要做幾發才回本，他愣了一下：「醫師，你要想的是客人會不會跑掉。」',
    choices: [
      {
        label: '簽。不能落後。',
        effects: { money: -60 },
        log: '機器進來那天，你在合約上簽了六個名字。它在診所待了五年：前八個月是新機器，後面四年是負債。',
      },
      {
        label: '不簽。',
        effects: { money: -10, self: 2 },
        log: '半年後有客人問：「你們沒有那台喔？」她轉頭就走。儀器商也沒有再打電話來。',
      },
    ],
  },
  {
    id: 'ae_rent',
    scene: 'aesthetic',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 2,
    text: '房東寄來續約通知，租金調漲兩成，理由是「這條街現在很熱鬧」。這條街熱鬧的原因，是又開了三家醫美。',
    effects: { money: -35, self: -2 },
    log: '你簽了。搬家的成本比漲租更貴，房東比你更早算出這件事。',
  },
  {
    id: 'ae_parallel_import',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '藥商業務壓低聲音：「醫師，一樣的東西，我這邊四折，很多診所都在用。」他把盒子推過來，包裝上的字你看不懂。',
    choices: [
      {
        label: '拒絕。',
        effects: { money: -15, self: 5 },
        log: '他把盒子收回去，臨走前說：「醫師你很有原則。」那個語氣，像在講一件很不划算的事。',
      },
      {
        label: '先進一批試試。',
        effects: { money: 30, self: -8 },
        set: (s) => {
          s.flags.greyGoods = true;
        },
        log: '客人打完的效果沒有差多少。差別在於，萬一出事，你手上沒有任何一張拿得出來的單據。',
      },
    ],
  },
  {
    id: 'ae_complication',
    scene: 'aesthetic',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 2,
    text: '一位客人打完玻尿酸，鼻翼開始發白、劇痛。血管栓塞。你叫助理拿溶解酶，同時發現自己的手很穩——十幾年的訓練，在這一刻派上用場。',
    effects: { self: 5, health: -3 },
    log: '兩小時後皮膚的顏色回來了。她一直道歉，問是不是自己體質不好。你搖頭。這件事不會寫成論文，也不會有人知道你救了她的鼻子。',
  },
  {
    id: 'ae_grey_complication',
    scene: 'aesthetic',
    mood: 'weary',
    stages: ['aesthetic'],
    once: true,
    weight: 3,
    cond: (s) => s.flags.greyGoods === true,
    text: '一位客人打完你上次進的那批藥，臉腫了五天，跑去別家診所處理。對方醫師問她：「妳知道妳打的是什麼嗎？」',
    effects: { money: -50, self: -8 },
    log: '你退了全額，附上一箱水果。她沒有告你。那天晚上你把倉庫剩下的盒子全部裝進袋子，診所的燈開到很晚。',
  },
  {
    id: 'ae_celebrity',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    cond: (s) => s.talents.social >= 5,
    text: '一位藝人指定你操作，條件是全程不能有第三個人在場，結束後要你去她的貼文按讚。經紀人另外交代：「如果有人問，我們沒來過。」',
    choices: [
      {
        label: '照做。',
        effects: { money: 60, self: -4 },
        log: '那則貼文寫「天生麗質」，底下三萬個讚。你也按了一個。',
      },
      {
        label: '婉拒這個條件。',
        effects: { money: -20, self: 4 },
        log: '經紀人很意外：「別家都可以啊。」他說得沒錯。隔週她出現在另一家診所的官網上，照片打了柔焦。',
      },
    ],
  },
  {
    id: 'ae_reported',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '衛生局來函：你的貼文被檢舉違反醫療廣告規定，「術後」兩個字不能用，前後對比照不能放。檢舉人不具名，但函裡附的截圖，是同業才會截的角度。',
    effects: { money: -8, self: -3 },
    log: '你把貼文刪了。同一週，對街那家發了一模一樣的內容，沒事。',
  },
  {
    id: 'ae_miss_or',
    scene: 'aesthetic',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 3,
    text: '下午三點，診所很安靜。你在雷射的機械聲裡，突然想起無影燈打開時那個「喀」的聲音。',
    effects: { self: -4 },
    log: '你有時候會在網路上看別人的手術影片，看完就把手機關掉，叫下一位客人。',
  },
  {
    id: 'ae_old_colleague',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '以前一起值班的學弟走進診所，是來打雷射的。他的白袍還掛在車上，說等一下要回去開晚上的刀。',
    choices: [
      {
        label: '問他科裡現在怎麼樣。',
        effects: { self: -4 },
        log: '他講了二十分鐘：人力、班表、新的評鑑。你聽著聽著發現那些抱怨你一句都插不上——你已經不在那張班表上了。',
      },
      {
        label: '什麼都不問，專心做他的臉。',
        effects: { self: -2 },
        log: '結帳時他要付錢，你說不用。他堅持刷了卡：「你這裡也是要成本的。」這句話比什麼都重。',
      },
    ],
  },
  {
    id: 'ae_income_empty',
    scene: 'home',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 3,
    cond: (s) => s.attrs.money >= 300,
    text: '你看著這個月的入帳，比你當主治時三個月加起來還多。你盯著那個數字看了一會兒，然後把手機蓋在桌上。',
    effects: { self: -4 },
    log: '你想找個人分享，通訊錄翻了兩遍，關掉了。',
  },
  {
    id: 'ae_family_dinner',
    scene: 'home',
    mood: 'lifted',
    stages: ['aesthetic'],
    weight: 3,
    cond: (s) => s.family.stage !== 'single' || s.family.kids > 0,
    text: '晚上七點，你在家。菜還是熱的，沒有人先吃。孩子問你今天怎麼那麼早，你說：「以後都會這麼早。」',
    effects: { familyBond: 12, self: 6 },
    log: '那頓飯你吃得很慢。這輩子第一次，吃飯不是一件要趕的事。',
  },
  {
    id: 'ae_tv_pointvalue',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '候診區的電視在播健保總額協商，跑馬燈寫「醫界憂點值續探底」。旁邊的客人抬頭看了一眼，轉頭問櫃檯：「我的音波什麼時候可以排？」',
    effects: { self: -3 },
    log: '櫃檯說下週三。電視繼續播，沒有人再抬頭。',
  },
  {
    id: 'ae_junior_ask',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '一個外科住院醫師學妹傳訊息來：「學長/學姊，可以請教一下……醫美好做嗎？」她沒有說為什麼問。',
    choices: [
      {
        label: '把難的地方全部講給她聽。',
        effects: { teaching: 2, self: 3 },
        log: '你講了業績、客訴、儀器貸款，還有那些開到三點的行銷會議。她回：「所以還是很累齁。」你說：「只是換一種累。」',
      },
      {
        label: '叫她再撐一下，外科需要人。',
        effects: { self: -5 },
        log: '你打了三行，刪掉，重打。最後送出的是：「你自己決定。」你沒有立場叫別人留在你已經離開的地方。',
      },
    ],
  },
  {
    id: 'ae_scalpel_again',
    scene: 'or',
    mood: 'wry',
    stages: ['aesthetic'],
    once: true,
    weight: 2,
    cond: (s) => s.attrs.clinical >= 30,
    text: '老同事打電話來：「我們缺人，你回來支援一台就好，你的手還在的。」你握著手機，發現自己已經在心裡把步驟數過一遍。',
    choices: [
      {
        label: '答應去一台。',
        effects: { clinical: 3, self: 6, health: -3 },
        stats: { surgeries: 1 },
        log: '你站上台，下第一刀之前深呼吸了一次。收尾時助手說：「學長/學姊你手真的沒退。」你笑了，沒說自己昨晚在家練了一整夜的打結。',
      },
      {
        label: '婉拒。',
        effects: { self: -6 },
        log: '你說最近很忙。掛掉電話，你把抽屜裡那副舊的持針器拿出來看了一下，又放回去。',
      },
    ],
  },
  {
    id: 'ae_closure_risk',
    scene: 'office',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 2,
    cond: (s) => s.attrs.money < 50,
    text: '會計師把報表翻到最後一頁：「以目前的來客數，撐得過八個月。要嘛降成本，要嘛拉業績。」你問還有沒有第三條路，他沒有回答。',
    choices: [
      {
        label: '裁掉兩個助理。',
        effects: { money: 25, self: -6 },
        log: '你親自跟她們談。其中一個說：「我知道，最近真的比較少人。」她離開前還把櫃檯整理過一遍。',
      },
      {
        label: '自己三個月不領薪水撐著。',
        effects: { money: -40, self: 3 },
        // 這一幕的條件只有存款低於 50 萬，單身、沒買房的人也會抽到。
        // 原本寫「房貸從別的戶頭扣下去」，等於替玩家宣告一個不存在的狀態。
        log: '你把自己的薪轉停掉。那三個月你沒有跟任何人講，直到固定扣款的帳單一張一張跳出來。',
      },
    ],
  },
  {
    id: 'ae_not_real_doctor',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 3,
    text: '客人在諮詢時說：「我想找『真的』醫生評估耶，你們醫美的……」她說到一半自己停住，說對不起。',
    choices: [
      {
        label: '把你的訓練履歷講給她聽。',
        effects: { self: -2 },
        log: '你講了住院醫師五年、專科執照、幾千台刀。她點頭：「哇，好厲害。」然後問這個療程可不可以打折。',
      },
      {
        label: '笑一笑，繼續評估。',
        effects: { self: -5 },
        log: '你什麼都沒說。你發現自己不太在乎了——這件事本身，比那句話更讓你難受。',
      },
    ],
  },
  {
    id: 'ae_review_bomb',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 3,
    text: '網路評論一夜之間多了七則一星，內容大同小異：效果不好、態度差。你翻遍病歷，其中五個帳號查無此人。',
    choices: [
      {
        label: '一則一則回覆。',
        effects: { self: -3, health: -1 },
        log: '你回到凌晨兩點，每一則都寫得很客氣。隔天又多了三則新的一星。',
      },
      {
        label: '花錢請人做評論管理。',
        effects: { money: -20 },
        log: '一週後總分回到四點六。行銷公司說這叫「聲量維護」。以前你的評價寫在病人的存活率上，不在星星上。',
      },
    ],
  },
  {
    id: 'ae_refund',
    scene: 'aesthetic',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 3,
    text: '一位客人做完三次療程，效果不如預期，帶著錄音筆來要求全額退費。她說：「不然我就貼上網。」',
    choices: [
      {
        label: '照合約走，不退。',
        effects: { money: 8, self: 2, health: -2 },
        log: '她真的貼了，還上了地方新聞的網路版。標題有你的診所名字，內文沒有寫她三次療程都簽了同意書。',
      },
      {
        label: '退。息事寧人。',
        effects: { money: -30, self: -4 },
        log: '她收了錢，貼文沒有出現。三個月後她又來了，這次要求先做後付。',
      },
    ],
  },
  {
    id: 'ae_photo_edit',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '行銷把術後照片傳來給你確認：光線換過、膚色亮了兩階、下巴的線條修過。「醫師，這樣比較好看嘛。」',
    choices: [
      {
        label: '要求換回原圖。',
        effects: { money: -10, self: 4 },
        log: '原圖貼出去，互動數只有平常的四分之一。行銷沒有再問過你的意見，只是之後的照片都「比較自然」了一點點。',
      },
      {
        label: '過。',
        effects: { self: -4 },
        log: '你按了通過。那張臉是真的，只是那個光不是。你知道下一位客人會拿著這張照片來，指著它說我要這樣。',
      },
    ],
  },
  {
    id: 'ae_repeat_client',
    scene: 'aesthetic',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 2,
    text: '一位客人半年內做了十一次療程，這次她指著鏡子說法令紋還是很深。你看著她的臉，找不到任何一個需要再動的地方。',
    choices: [
      {
        label: '拒絕，請她先休息一陣子。',
        effects: { money: -15, self: 5 },
        log: '她很生氣：「你是不是覺得我很煩？」隔週她在別家做了，照片發在限時動態，標註了那家診所。',
      },
      {
        label: '做。是她自己要的。',
        effects: { money: 15, self: -6 },
        log: '躺上治療床時她問：「這次會不一樣吧？」你說會。這句話你已經說到第十一次。',
      },
    ],
  },
  {
    id: 'ae_no_show',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '下午三個預約全部沒來，其中一個在對話框裡回「臨時有事」。機器已經開機、藥已經退冰、診已經留好。',
    effects: { money: -12, self: -2 },
    log: '你在空診間坐了一個下午。以前你嫌病人太多，現在你嫌時間太多，兩種你都不喜歡。',
  },
  {
    id: 'ae_minor',
    scene: 'aesthetic',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '一位高中生被媽媽帶來諮詢隆鼻。媽媽說：「她考完學測，當作禮物。」女生全程低著頭滑手機。',
    choices: [
      {
        label: '請她們等成年再說。',
        effects: { money: -20, self: 5 },
        log: '媽媽不太高興：「別家都可以做啊。」你說那你們可以去別家。女生走之前抬頭看了你一眼，你分不出來那是失望還是別的。',
      },
      {
        label: '評估後安排手術。',
        effects: { money: 35, self: -6 },
        log: '手術很順利。三個月後回診，她說同學都在問她去哪裡做的。你把這句話當成好評，收下了。',
      },
    ],
  },
  {
    id: 'ae_group_buy',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '團購主找上門，開價買斷五百組療程，一組的價格連耗材都不夠。「醫師，這是曝光，不是賺錢。」',
    choices: [
      {
        label: '接。先把人衝進來。',
        effects: { money: 40, self: -4 },
        log: '三個月做了四百多組。客人拿著折扣碼來，做完就走，沒有一個回購。那三個月裡，你的手做的是這輩子最重複的動作。',
      },
      {
        label: '不接。',
        effects: { money: -15, self: 3 },
        log: '團購主轉去對街，那家的排隊照片上了新聞。半年後那家收掉了，換人接手，招牌還是原來的顏色。',
      },
    ],
  },
  {
    id: 'ae_six_pm',
    scene: 'home',
    mood: 'lifted',
    stages: ['aesthetic'],
    weight: 3,
    text: '晚上六點，你站在自家樓下的紅綠燈前。你發現這條路上有些店你從來沒看過——它們都是六點以後才亮燈的。',
    effects: { self: 5, health: 2 },
    log: '你買了一杯豆漿，慢慢走回家。十幾年來，這是第一次你在天還沒全黑的時候走這段路。',
  },
  {
    id: 'ae_bystander_cpr',
    scene: 'corridor',
    mood: 'lifted',
    stages: ['aesthetic'],
    once: true,
    weight: 2,
    text: '百貨公司地下街，一個男人倒下。你跪下去的時候手比腦子快：壓胸、要 AED、指派旁邊的人打 119，一句話都沒有停頓。',
    effects: { self: 8, health: -2 },
    stats: { livesSaved: 1 },
    log: '救護車走了以後，圍觀的人問你是不是醫生。你說是。那一刻你發現自己答得很快，沒有先想「哪一種」。',
  },
  {
    id: 'ae_licence',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 1,
    text: '一位認識的老闆要開診所，缺一張執照掛名：「你什麼都不用做，一個月十萬。」他強調療程會找別的醫師來執行。',
    choices: [
      {
        label: '拒絕。',
        effects: { self: 5 },
        log: '他笑你太保守。三年後那家診所出事上了新聞，掛名的那位醫師被移送，判決書上寫的是他的名字。',
      },
      {
        label: '答應。錢很好賺。',
        effects: { money: 80, self: -10 },
        set: (s) => {
          s.flags.nomineeClinic = true;
        },
        log: '你每個月收一筆不用做事的錢，單獨存在一個帳戶裡，從來沒有動過。你也說不清楚為什麼。',
      },
    ],
  },
  {
    id: 'ae_conference',
    scene: 'office',
    mood: 'weary',
    stages: ['aesthetic'],
    once: true,
    weight: 2,
    text: '外科醫學會年會，你用舊的會員身分報名。走進會場，海報區站著一群很年輕的住院醫師，你認識的人一個都不在。',
    effects: { self: -5 },
    log: '午餐你坐最後一排。有人認出你：「學長/學姊好久不見，現在在哪裡高就？」你講了診所的名字，對方說：「喔——很好啊。」然後就沒有然後了。',
  },
  {
    id: 'ae_consultant_leave',
    scene: 'office',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    text: '你的王牌諮詢師離職，一週後在對街上班。你的老客戶名單，跟著她走了三分之一。',
    effects: { money: -45, self: -4 },
    log: '你這才想通：那些人是來找她的，不是來找你的。你的技術從頭到尾都不是這門生意的主角。',
  },
  {
    id: 'ae_kid_form',
    scene: 'home',
    mood: 'wry',
    stages: ['aesthetic'],
    weight: 2,
    cond: (s) => s.family.kids > 0,
    text: '孩子的學校資料要填家長職業。你寫「醫師」，孩子在旁邊問：「可是你不是不在醫院了嗎？」',
    choices: [
      {
        label: '解釋醫美也是醫療。',
        effects: { familyBond: 2, self: -3 },
        log: '你講了執照、專科、訓練。孩子聽完點頭：「喔。那你現在還會救人嗎？」',
      },
      {
        label: '改寫「服務業」。',
        effects: { familyBond: 3, self: -5 },
        log: '你寫了。孩子看了看，說：「這樣同學比較聽得懂。」這句話沒有惡意，所以更難反駁。',
      },
    ],
  },
  {
    id: 'ae_mediation',
    scene: 'court',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 2,
    text: '衛生局的醫療爭議調解。對方帶了律師，你帶了病歷和同意書。調解委員一開口就問：「醫師，你們是不是廣告過『零風險』？」',
    choices: [
      {
        label: '澄清那是行銷寫的文案。',
        effects: { money: -15, self: -4 },
        log: '委員說：「那也是你們診所發的。」你想起那則貼文你確實看過，也確實按了通過。',
      },
      {
        label: '直接談和解金。',
        effects: { money: -35, self: -3 },
        log: '半小時結束。走出調解室，你發現自己在這種場合已經不會緊張了。這不是好消息。',
      },
    ],
  },
  {
    id: 'ae_hands_rust',
    scene: 'aesthetic',
    mood: 'weary',
    stages: ['aesthetic'],
    weight: 2,
    cond: (s) => s.attrs.clinical < 45,
    text: '你在幫客人縫一個小傷口，三針。縫到第二針的時候，你發現自己在猶豫進針的角度。',
    effects: { self: -6 },
    log: '傷口縫得很漂亮，客人完全看不出來。只有你知道，那個猶豫在三年前並不存在。',
  },
];
