// 同梯・林致遠。另一個你。
//
// 弧線：0 一起苦 → 1 他動搖 → 2 分岔 → 3 收束。
// 分岔不是骰出來的：他問「你會走嗎」，你怎麼答，他就走哪一條。
// path 記在 s.people.peer.path，之後每一幕都只認那個字。
import { advance } from '../characters.js';

const P = (s) => s.people.peer;

export const PEER_EVENTS = [
  // ───────── 第 0 幕：一起苦 ─────────
  {
    id: 'p_bread',
    scene: 'oncall',
    mood: 'weary',
    priority: true,
    stages: ['resident'],
    once: true,
    weight: 4,
    cond: (s) => P(s).stage === 0,
    text: '值班室櫃子裡剩最後一包麵包，效期是前天。林致遠掰成兩半，遞一半給你：「還沒長毛。」',
    effects: { self: 3, health: -1 },
    bond: { peer: 5 },
    log: '你們配自來水吃完，然後各自被 call 走。那個櫃子後來一直有麵包，因為你們兩個都會偷偷補。',
  },
  {
    id: 'p_cover',
    scene: 'oncall',
    mood: 'weary',
    priority: true,
    stages: ['resident'],
    once: true,
    weight: 3,
    cond: (s) => P(s).stage === 0,
    text: '林致遠的爸爸被送去別家醫院的急診。他站在值班室門口，手機還握在手上，沒有講話。',
    choices: [
      {
        label: '「你去。這裡我頂。」',
        effects: { self: 3, health: -4 },
        bond: { peer: 10 },
        log: '你連著值了三十個小時。他隔天中午回來，帶了兩個便當，什麼都沒說。那頓飯你們吃得很安靜。',
      },
      {
        label: '「我明天有刀，你先打電話問問看。」',
        effects: { self: -4 },
        bond: { peer: -8 },
        log: '他說「也對」，坐回床邊繼續打病歷。他爸爸後來沒事。這件事誰都沒再提，只是他再也沒找你換過班。',
      },
    ],
  },
  {
    id: 'p_scold',
    scene: 'or',
    mood: 'weary',
    priority: true,
    stages: ['resident'],
    weight: 3,
    cond: (s) => P(s).stage === 0,
    text: '晨會，主任把你和林致遠並排叫到前面，從病歷寫法罵到站姿，罵了二十分鐘。全科三十幾個人看著。',
    effects: { self: -4, clinical: 2 },
    bond: { peer: 6 },
    log: '散會後你們在樓梯間站了一會兒。林致遠說：「他罵你那段比較久。」你說：「我在算你的。」然後兩個人都笑了。',
  },
  {
    id: 'p_cry',
    scene: 'oncall',
    mood: 'weary',
    priority: true,
    stages: ['resident'],
    once: true,
    weight: 4,
    cond: (s) => P(s).stage === 0 && s.age >= 28,
    text: '凌晨兩點你回值班室拿東西，聽見廁所裡有聲音。門縫底下沒有光。是林致遠。',
    choices: [
      {
        label: '退出去，在護理站等他。',
        effects: { self: -5 },
        bond: { peer: 8 },
        memory: '你聽見林致遠在值班室的廁所裡哭，你退了出去，假裝沒聽見。',
        set: (s) => advance(s, 'peer', 1),
        log: '十分鐘後他出來，洗了臉，說：「12 床那條 CVP 我來打。」你說好。這件事你們一輩子沒有提過。',
      },
      {
        label: '敲門問他還好嗎。',
        effects: { self: -3 },
        bond: { peer: -5 },
        set: (s) => advance(s, 'peer', 1),
        log: '門開了一條縫：「沒事，眼睛進東西。」然後關上。隔天他跟你講話的時候，眼睛看的是你身後那面牆。',
      },
    ],
  },

  // ───────── 第 1 幕：他動搖 ─────────
  {
    id: 'p_drift',
    scene: 'office',
    mood: 'wry',
    priority: true,
    stages: ['resident', 'attending'],
    weight: 3,
    cond: (s) => P(s).stage >= 1 && !P(s).path,
    text: '你借林致遠的電腦查文獻。瀏覽器還開著三個分頁：診所徵才、醫美教育訓練、房貸試算。他從後面走過來把視窗關掉：「隨便看看。」',
    effects: { self: -3 },
    bond: { peer: 2 },
    log: '你什麼都沒問。回到自己座位，你也點開了同一個網站，看了兩分鐘，關掉。',
  },
  {
    id: 'p_wife',
    scene: 'home',
    mood: 'wry',
    priority: true,
    stages: ['resident', 'attending'],
    weight: 2,
    cond: (s) => P(s).stage >= 1 && !P(s).path,
    text: '尾牙。林致遠的太太第一次來，坐在你旁邊。她問：「他一個月可以在家吃幾次晚餐？」你算了一下，不敢講。',
    effects: { self: -3 },
    bond: { peer: 3 },
    log: '你說最近比較忙。她笑了笑：「三年前你也是這樣講。」那一頭林致遠正被主任敬酒，站著，杯子舉得比誰都高。',
  },
  {
    id: 'p_fork',
    scene: 'oncall',
    mood: 'weary',
    priority: true,
    stages: ['resident', 'attending'],
    once: true,
    weight: 4,
    cond: (s) => !P(s).path && s.age >= 30,
    text: '交完班，凌晨四點半。林致遠沒有走，坐在下鋪，白袍還沒脫。他忽然問：「欸，你會走嗎？」',
    choices: [
      {
        label: '「不會。總得有人開刀。」',
        effects: { self: 4 },
        bond: { peer: 8 },
        memory: '林致遠問你會不會走，你說不會，於是他也留了下來。',
        set: (s) => {
          advance(s, 'peer', 2);
          P(s).path = 'stayed';
        },
        log: '他想了很久，說：「好，那我也不走。」你那時候以為這是一句好話。',
      },
      {
        label: '「你走吧。你已經撐夠久了。」',
        effects: { self: -3 },
        bond: { peer: 10 },
        memory: '林致遠問你會不會走，你叫他走。',
        set: (s) => {
          advance(s, 'peer', 2);
          P(s).path = 'left';
        },
        log: '他愣住，眼眶紅了：「你是第一個這樣跟我講的人。」四個月後他遞辭呈。會辦單上有一欄要同科醫師簽名，他拿來給你簽。',
      },
      {
        label: '「我不知道。」',
        effects: { self: -5 },
        bond: { peer: -4 },
        memory: '林致遠問你會不會走，你說你不知道。',
        set: (s) => {
          advance(s, 'peer', 2);
          P(s).path = 'broken';
        },
        log: '你們坐到天亮，誰都沒有再開口。他沒有走，也沒有再拿這個問題問過任何人。',
      },
    ],
  },

  // ───────── 第 2 幕・left：他離開外科 ─────────
  {
    id: 'p_left_clinic',
    scene: 'aesthetic',
    mood: 'wry',
    priority: true,
    stages: ['attending'],
    once: true,
    weight: 3,
    cond: (s) => P(s).path === 'left' && s.age >= 36,
    text: '林致遠的診所在捷運站出口旁邊，落地窗，有咖啡機。他穿短袖，氣色比住院醫師那五年加起來都好。牆上的看診時間寫到下午五點半。',
    choices: [
      {
        label: '替他高興。',
        effects: { self: 4 },
        bond: { peer: 6 },
        log: '你們吃了晚餐，七點半就散了——他要回去看小孩的聯絡簿。走出來你看了一下手錶，發現自己的七點半已經空了十年。',
      },
      {
        label: '問他會不會想念開刀。',
        effects: { self: -4 },
        bond: { peer: 3 },
        log: '他攪著咖啡想了很久：「會啊。」停一下又說：「但我不想念那個累到會恨病人的自己。」你沒有接話。',
      },
    ],
  },
  {
    id: 'p_left_referral',
    scene: 'clinic',
    mood: 'wry',
    priority: true,
    stages: ['attending'],
    weight: 2,
    cond: (s) => P(s).path === 'left' && s.age >= 38,
    text: '門診來了一位病人，手上拿著林致遠開的轉診單。字跡還是那個字跡，最後一行寫著：「這個我不會處理了，麻煩你。」',
    effects: { clinical: 2, self: -2 },
    stats: { surgeries: 1, livesSaved: 1 },
    bond: { peer: 4 },
    log: '那台刀開了六小時。晚上他傳訊息問結果，你回「拿乾淨了」。他回：「謝謝你。」隔了半小時又傳一句：「對不起。」',
  },
  {
    id: 'p_left_close',
    scene: 'home',
    mood: 'weary',
    priority: true,
    stages: ['attending'],
    once: true,
    weight: 4,
    cond: (s) => P(s).path === 'left' && s.age >= 50,
    text: '半夜，林致遠傳來一個很大的檔案：他把住院醫師那五年的手術紀錄本一頁一頁掃描起來，四百多台。他問你要不要留一份。',
    choices: [
      {
        label: '說要。',
        effects: { self: -5 },
        bond: { peer: 8 },
        memory: '林致遠離開外科二十年後，把他當年的手術紀錄傳給你，你收下了。',
        set: (s) => advance(s, 'peer', 3),
        log: '傳了十分鐘。最後一頁停在他離職前一週。他說：「這些東西沒有地方可以放。放你那裡，至少還算數。」',
      },
      {
        label: '問他為什麼現在才整理。',
        effects: { self: -6 },
        bond: { peer: 4 },
        memory: '你問林致遠為什麼現在才整理那些手術紀錄，他說連他自己都快忘了。',
        set: (s) => advance(s, 'peer', 3),
        log: '他隔了很久才回：「我女兒問我以前在醫院做什麼，我答不出來。」然後又補一句：「我發現連我自己都快忘了。」',
      },
    ],
  },

  // ───────── 第 2 幕・stayed：他留下來 ─────────
  {
    id: 'p_stayed_backup',
    scene: 'or',
    mood: 'weary',
    priority: true,
    stages: ['attending'],
    weight: 3,
    cond: (s) => P(s).path === 'stayed' && s.age >= 36,
    text: '半夜的大出血，你一個人壓不住。你打給林致遠，他沒有問是什麼刀，只說：「二十分鐘。」',
    effects: { clinical: 2, self: 6, health: -3 },
    stats: { surgeries: 1, livesSaved: 1 },
    bond: { peer: 8 },
    log: '他十八分鐘就到，睡衣外面套一件白袍。血止住的時候是四點十分。他洗手的時候說：「你欠我一頓。」你欠他七頓了。',
  },
  {
    id: 'p_stayed_cost',
    scene: 'corridor',
    mood: 'weary',
    priority: true,
    stages: ['attending'],
    once: true,
    weight: 3,
    cond: (s) => P(s).path === 'stayed' && s.age >= 45,
    text: '更衣室，林致遠的置物櫃門開著。裡面一排藥盒：血壓、血脂、胃藥，還有一罐沒有標籤的。他從你後面伸手把門關上：「年紀到了嘛。」',
    effects: { self: -5 },
    bond: { peer: 5 },
    log: '你想起他二十八歲的時候可以連值三天。那排藥盒你數過了，六罐——跟你自己抽屜裡那排一樣多。',
  },
  {
    id: 'p_stayed_close',
    scene: 'or',
    mood: 'weary',
    priority: true,
    stages: ['attending'],
    once: true,
    weight: 4,
    cond: (s) => P(s).path === 'stayed' && s.age >= 50,
    text: '你和林致遠站在刀房外面等病人上台。他忽然說：「我兒子今年畢業。」你問他選哪一科，他說皮膚科。停了兩秒，他補一句：「我叫他去的。」',
    choices: [
      {
        label: '說你懂。',
        effects: { self: -6 },
        bond: { peer: 8 },
        memory: '林致遠叫他兒子別走外科，你告訴他你懂。',
        set: (s) => advance(s, 'peer', 3),
        log: '他點點頭，沒有再說什麼。那台刀你們一起開，配合得像二十年前。收尾時他問：「我們這一梯，還剩幾個？」你算出來了，沒有講。',
      },
      {
        label: '問他後不後悔留下來。',
        effects: { self: -4 },
        bond: { peer: 3 },
        memory: '你問林致遠後不後悔留下來，他說他不敢想。',
        set: (s) => advance(s, 'peer', 3),
        log: '他笑了一下：「不敢想。想了就撐不下去了。」然後推門進去洗手。那個背影你看了很久，才跟上去。',
      },
    ],
  },

  // ───────── 第 2 幕・broken：他留下來，但垮了 ─────────
  {
    id: 'p_broken_dark',
    scene: 'office',
    mood: 'weary',
    priority: true,
    stages: ['attending'],
    weight: 3,
    cond: (s) => P(s).path === 'broken' && s.age >= 36,
    text: '林致遠的刀量掉了一半。晨會他坐最後一排，別人報告的時候他一直看窗外。更衣室裡你看見他手上有一板藥，白色的，鋁箔背面被剪掉了。',
    choices: [
      {
        label: '約他吃飯，什麼都不問。',
        effects: { self: -3, health: -1 },
        bond: { peer: 10 },
        log: '你們吃了兩個小時，講的全是刀。散場他說：「謝謝你沒有問。」你才知道他這半年被問過很多次。',
      },
      {
        label: '勸他去看身心科。',
        effects: { self: -2 },
        bond: { peer: -7 },
        log: '他反應很大：「我沒事。」然後壓低聲音：「而且掛號會留紀錄，你知道吧。」那之後他看到你會先笑一下，笑完就走開。',
      },
    ],
  },
  {
    id: 'p_broken_gone',
    scene: 'oncall',
    mood: 'weary',
    priority: true,
    stages: ['attending'],
    once: true,
    weight: 4,
    cond: (s) => P(s).path === 'broken' && s.age >= 44,
    text: '林致遠的太太年初帶著孩子搬走了，離婚協議是律師代簽的——那天他在開刀。三月的一個星期一，他沒有來上班，手機關機。第四天，警察在南部一間汽車旅館找到他，人還在。',
    choices: [
      {
        label: '請假南下，把他接回來。',
        effects: { self: -8, health: -3 },
        bond: { peer: 12 },
        memory: '林致遠消失了四天，你請假南下，把他接了回來。',
        log: '你開了五個小時的車。回程他坐副駕，一路沒講話，過收費站的時候才說：「你不用來的。」你說：「我知道。」',
      },
      {
        label: '通知他家人，讓家屬處理。',
        effects: { self: -6 },
        bond: { peer: -7 },
        memory: '林致遠消失了四天，你把電話打給了他哥哥。',
        log: '他哥哥去接的。三週後他回來上班，在走廊上跟你點頭，叫了你的全名。同梯十八年，他從來沒有這樣叫過你。',
      },
    ],
  },
  {
    id: 'p_broken_close',
    scene: 'corridor',
    mood: 'weary',
    priority: true,
    stages: ['attending'],
    once: true,
    weight: 4,
    cond: (s) => P(s).path === 'broken' && s.age >= 50,
    text: '林致遠這幾年只看門診，不排刀了。你在走廊上遇到他推著一台超音波，他說：「這台比較輕。」',
    effects: { self: -7 },
    bond: { peer: 4 },
    set: (s) => advance(s, 'peer', 3),
    log: '你想起二十六歲那年他一個人扛兩箱器械爬四樓，還嫌電梯太慢。他推著機器往前走，經過刀房門口的時候，沒有轉頭。',
  },
];
