// PGY(25-26 歲)。還沒選科，什麼都做，什麼都不會。
export const PGY_EVENTS = [
  {
    id: 'pgy_scut',
    scene: 'corridor',
    mood: 'weary',
    stages: ['pgy'],
    weight: 3,
    text: '接不完的 NG、導尿、抽血、寫不完的病歷。學長說：「這就是 PGY，習慣就好。」',
    effects: { health: -3 },
    log: '你開始習慣了。這件事本身有點可怕。',
  },
  {
    id: 'pgy_first_death',
    scene: 'or',
    mood: 'weary',
    stages: ['pgy'],
    once: true,
    weight: 2,
    text: '你第一次參與急救。壓胸時肋骨斷裂的觸感，和主治宣告死亡時牆上時鐘的位置，你都會記得很久。',
    effects: { self: -2, health: -2 },
    log: '那晚你在值班室坐了很久，沒有開燈。',
  },
  {
    id: 'pgy_mentor',
    scene: 'or',
    mood: 'lifted',
    stages: ['pgy'],
    once: true,
    cond: (s) => s.talents.dexterity >= 6,
    text: '值班夜，總醫師帶你開了人生第一台闌尾。收尾時他看著你的手：「手感不錯，考慮外科？」',
    effects: { self: 5 },
    log: '你走出開刀房，天還沒亮，但你睡意全無。',
  },
  {
    id: 'pgy_salary_talk',
    scene: 'home',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '大學同學會。念資工的室友剛拿到新加坡的 offer，年薪是你的三倍。他問你：「你們醫師很賺吧？」',
    choices: [
      {
        label: '笑著說還好',
        effects: { self: -2 },
        log: '你笑得很得體。你在醫院練得最好的，常常是這個。',
      },
      {
        label: '老實講薪水',
        effects: { self: 2 },
        log: '整桌安靜了三秒。然後有人說：「可是你們是在救人啊。」你點點頭。這句話你之後會聽到很多次，通常在別人不想付錢的時候。',
      },
    ],
  },
  {
    id: 'pgy_specialty',
    scene: 'corridor',
    stages: ['pgy'],
    once: true,
    forced: (s) => s.age === 26,
    // 手感天賦 1 的人不會被說「你的手很穩」。學長說的話要看得到的東西。
    text: (s) =>
      s.talents.dexterity >= 5
        ? 'PGY 結束，選科的時刻到了。外科的學長說：「你的手很穩，來吧，總得有人開刀。」同梯的說：「別傻了，現在誰走外科？」'
        : 'PGY 結束，選科的時刻到了。外科的學長說：「你肯站，肯站就夠了，總得有人開刀。」同梯的說：「別傻了，現在誰走外科？」',
    choices: [
      {
        label: '選外科。總得有人開刀。',
        effects: { self: 5 },
        log: '你簽下外科住院醫師志願書。歡迎來到戰場。',
      },
      {
        label: '選別科。那裡有你想要的生活。',
        set: (s) => {
          s.flags.exitNow = true;
          s.flags.exitCause = 'exit-specialty';
        },
        log: '你選擇了另一條路。學長拍拍你的肩，沒有多說什麼——你們都明白，每條路有每條路的代價。',
      },
    ],
  },
  {
    id: 'pgy_handover',
    scene: 'corridor',
    mood: 'weary',
    stages: ['pgy'],
    weight: 3,
    text: '交班。上一班留下六個 pending，其中三個沒寫原因。你問學姊該怎麼辦，她說：「你自己重看一次比較快。」',
    effects: { health: -2, clinical: 1 },
    log: '你重看了一次。她說得對，這比較快。這件事沒有人會記在任何一張表上。',
  },
  {
    id: 'pgy_family_ask',
    scene: 'clinic',
    mood: 'wry',
    stages: ['pgy'],
    weight: 3,
    text: '家屬堵在護理站門口：「醫生，我爸到底什麼時候可以出院？」你才剛接這床三小時，病歷還沒看完。',
    choices: [
      {
        label: '老實說你剛接手，先去看病歷。',
        effects: { self: 1 },
        log: '家屬皺了眉：「怎麼又換醫生？」你解釋了輪班制度，他沒有聽進去。你也不怪他。',
      },
      {
        label: '含糊帶過，說會再評估。',
        effects: { self: -2, clinical: -1 },
        log: '家屬滿意地走了。你回到電腦前，才發現這床昨天就該安排出院。',
      },
    ],
  },
  {
    id: 'pgy_night_call',
    scene: 'oncall',
    mood: 'weary',
    stages: ['pgy'],
    weight: 3,
    text: '凌晨三點，護理師 call 你：「16 床睡不著，要不要開安眠藥？」你在黑暗裡摸到手機，花了四秒鐘想起自己在哪裡。',
    effects: { health: -3 },
    log: '你開了藥。掛掉電話後，你自己睡不著了。',
  },
  {
    id: 'pgy_ward_round',
    scene: 'corridor',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '晨會迴診。主任問你 12 床的鉀離子多少，你答不出來。整排人站在走廊上等你翻手機。',
    choices: [
      {
        label: '老實說不知道，回去查。',
        effects: { clinical: 2, self: -2 },
        log: '主任只說了句「下次先看」。那天之後，你每天六點半就到，把數字全背起來。',
      },
      {
        label: '賭一把，講一個大概的數字。',
        effects: { self: -4 },
        log: '你講錯了。主任沒有當場拆穿，只是「嗯」了一聲。那個「嗯」你記了很久。',
      },
    ],
  },
  {
    id: 'pgy_consent',
    scene: 'clinic',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '你被叫去簽術前同意書。病人問：「這個手術會不會有危險？」上面印著十四項併發症，最後一項是死亡。',
    choices: [
      {
        label: '一項一項唸完。',
        effects: { self: 2, health: -1 },
        log: '你唸了二十分鐘。病人的太太越聽臉越白，最後問：「那不開會怎樣？」你也一項一項回答了。',
      },
      {
        label: '講重點就好，不要嚇到人。',
        effects: { self: -2 },
        log: '你講了三分鐘。他們簽了。你知道那張紙的功能不是說明，是免責。',
      },
    ],
  },
  {
    id: 'pgy_er_shift',
    scene: 'corridor',
    mood: 'weary',
    stages: ['pgy'],
    weight: 3,
    text: '急診支援。走廊上排了二十四張推床，最外面那張已經等了十一個小時。護理長說：「今天算好的。」',
    effects: { health: -4, clinical: 2 },
    log: '你在人縫裡側身走過去。有個阿嬤抓住你的袖子問什麼時候輪到她，你只能說「快了」。',
  },
  {
    id: 'pgy_drunk',
    scene: 'corridor',
    mood: 'weary',
    stages: ['pgy'],
    weight: 2,
    text: '酒醉病人揮拳打翻了治療車，護理師的手臂被抓出三道血痕。保全五分鐘後才到。',
    choices: [
      {
        label: '堅持報警並提告。',
        effects: { self: 3, health: -2 },
        log: '筆錄做到凌晨四點。三個月後不起訴，理由是「酒後失去辨識能力」。護理師沒有再提這件事。',
      },
      {
        label: '算了，大家都很累。',
        effects: { self: -4 },
        log: '你們把地板收乾淨，繼續上班。這種「算了」在醫院裡多到可以鋪成一條路。',
      },
    ],
  },
  {
    id: 'pgy_thanks',
    scene: 'clinic',
    mood: 'lifted',
    stages: ['pgy'],
    once: true,
    weight: 2,
    text: '一位阿伯出院那天，硬塞給你一袋自己種的芭樂。他說：「醫師，你那天半夜有來看我，我知道。」',
    effects: { self: 8 },
    log: '你其實不記得是哪一晚了——那陣子每一晚你都在。但這袋芭樂你記得很久。',
  },
  {
    id: 'pgy_notes',
    scene: 'office',
    mood: 'wry',
    stages: ['pgy'],
    weight: 3,
    text: '病歷書寫評核退件。理由：「主訴未使用病人原話。」你寫的是「腹痛三天」，病人說的是「肚子痛甲欲死」。',
    effects: { self: -2, health: -1 },
    log: '你改成「肚子痛甲欲死」。系統跳出提醒：請使用正式醫學用語。',
  },
  {
    id: 'pgy_jcaho',
    scene: 'office',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '醫院評鑑週。你被要求把過去三個月的教學紀錄補齊，格式要統一，字體要一致，今晚之前。',
    effects: { health: -3, self: -3 },
    log: '你補到凌晨兩點。那些教學是真的發生過的，只是當時沒有人有空記錄。評鑑那天，委員翻了三頁就放下了。',
  },
  {
    id: 'pgy_senior_quit',
    scene: 'oncall',
    mood: 'weary',
    stages: ['pgy'],
    once: true,
    weight: 2,
    text: '帶你的學長離職了。最後一天他把值班室櫃子裡的東西收一收，只有一個馬克杯和一本翻爛的手術學。',
    effects: { self: -4 },
    log: '他把那本書留給你，說：「你比我適合。」你不知道那是稱讚還是詛咒。',
  },
  {
    id: 'pgy_first_suture',
    scene: 'or',
    mood: 'lifted',
    stages: ['pgy'],
    once: true,
    cond: (s) => s.talents.dexterity >= 4,
    text: '你第一次獨立縫合。傷口不長，七針。你縫得很慢，但每一針的間距都一樣。',
    effects: { clinical: 3, self: 5 },
    log: '學長看了一眼：「還可以。」你知道「還可以」在外科是什麼意思。你偷偷高興了一整天。',
  },
  {
    id: 'pgy_hours',
    scene: 'office',
    mood: 'wry',
    stages: ['pgy'],
    weight: 3,
    text: '住院醫師工時上限規定上路，每週不得超過 80 小時。系統要你自己登錄工時，而系統只讓你填到 80。',
    effects: { self: -4 },
    log: '你填了 80。實際上是 94。這個數字沒有地方可以填，所以它不存在。',
  },
  {
    id: 'pgy_covid_drill',
    scene: 'corridor',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '院內感染演練。你穿著全套防護裝備在走廊上站了四十分鐘，等長官拍完照。',
    effects: { health: -2, self: -2 },
    log: '照片隔天上了醫院粉專，標題是「守護民眾健康的堅強後盾」。留言區有人問醫護加薪了沒。',
  },
  {
    id: 'pgy_dietician',
    scene: 'corridor',
    mood: 'lifted',
    stages: ['pgy'],
    weight: 2,
    text: '一位營養師在茶水間看你連續第三天吃同一款泡麵，默默放了一顆茶葉蛋在你桌上。',
    effects: { self: 4, health: 1 },
    log: '你吃掉了。那是那個禮拜你唯一吃到的蛋白質，也是唯一有人注意到你的時刻。',
  },
  {
    id: 'pgy_mistake',
    scene: 'clinic',
    mood: 'weary',
    stages: ['pgy'],
    once: true,
    weight: 2,
    text: '你把兩床的抽血單開反了。護理師在抽之前發現，叫住了你。',
    choices: [
      {
        label: '主動通報異常事件。',
        effects: { self: 4, clinical: 2 },
        log: '你填了通報單。討論會上沒有人罵你，反而改了單據的排列方式。你第一次覺得這個系統有在運作。',
      },
      {
        label: '沒有造成傷害，就算了。',
        effects: { self: -3 },
        log: '沒有人知道。三個月後，別人犯了同一個錯，而那次沒有人叫住他。',
      },
    ],
  },
  {
    id: 'pgy_relative_call',
    scene: 'home',
    mood: 'wry',
    stages: ['pgy'],
    weight: 3,
    text: '遠房阿姨打電話來，傳了一張別人的健檢報告要你看。「你是醫生嘛，幫我看一下就好。」',
    choices: [
      {
        label: '認真看完，回她建議。',
        effects: { health: -1, self: 1 },
        log: '你花了四十分鐘。她回：「喔好，謝謝。」隔週她又傳了三張來。',
      },
      {
        label: '請她掛號給專科醫師。',
        effects: { self: -1 },
        log: '她說：「掛號好麻煩喔，你們自己人不是看一下就知道？」你解釋了責任歸屬，她已經在傳下一張了。',
      },
    ],
  },
  {
    id: 'pgy_np',
    scene: 'corridor',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '專科護理師比你熟練十倍。她一邊教你打中心靜脈導管，一邊處理三通電話。',
    effects: { clinical: 3, self: -1 },
    log: '你問她做多久了。「八年。」你想起她的薪水，再想起自己的，發現這兩個數字都不太對。',
  },
  {
    id: 'pgy_teaching_clinic',
    scene: 'clinic',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '教學門診。主治要你先問診，他在旁邊看。你問到第三個問題就卡住了，病人開始看牆上的時鐘。',
    effects: { clinical: 2, self: -2 },
    log: '結束後主治說：「問診不是背題目，是聽人講話。」這句話你花了十年才真的懂。',
  },
  {
    id: 'pgy_lottery',
    scene: 'oncall',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '值班表出來了。中秋、國慶、跨年，三個都是你。同梯的說：「電腦排的，很公平。」',
    effects: { self: -3, health: -1 },
    log: '你查了一下，那位同梯三個都不用值。電腦大概也覺得他比較需要休息。',
  },
  {
    id: 'pgy_first_death_cert',
    scene: 'corridor',
    mood: 'weary',
    stages: ['pgy'],
    once: true,
    text: '你第一次開死亡診斷書。手寫，不能塗改，寫錯要重來。你寫錯了兩次，因為手在抖。',
    effects: { self: -5, health: -2 },
    log: '家屬在門外等。第三張你寫對了，交出去的時候，你注意到自己的字比平常端正很多。',
  },
  {
    id: 'pgy_gift_refuse',
    scene: 'clinic',
    mood: 'wry',
    stages: ['pgy'],
    weight: 1,
    text: '家屬硬要塞紅包。你推回去，他又塞過來，來回三次，最後他說：「這樣我很不安心。」',
    effects: { self: 2 },
    log: '你說不收才安心。他不太懂，但收回去了。這件事沒有人看見，也不會有人記錄。',
  },
  {
    id: 'pgy_sleep_debt',
    scene: 'oncall',
    mood: 'weary',
    stages: ['pgy'],
    weight: 3,
    cond: (s) => s.alloc.personal < 15,
    text: '你在等電梯的時候睡著了，站著。醒來時電梯門開了又關，不知道過了幾趟。',
    effects: { health: -5, self: -2 },
    log: '你走樓梯上去。這樣比較不會睡著。',
  },
  {
    id: 'pgy_choose_or',
    scene: 'or',
    mood: 'lifted',
    stages: ['pgy'],
    weight: 2,
    cond: (s) => s.alloc.clinical >= 60,
    text: '你自願跟了一台十小時的刀，只為了站在旁邊拉鉤。全程沒有人跟你說話。',
    effects: { clinical: 3, health: -4, self: 3 },
    log: '結束時你的手臂舉不起來，但你把整台刀的步驟默背了一遍。有些東西，只能用站的學。',
  },
  {
    id: 'pgy_news_shortage',
    scene: 'home',
    mood: 'wry',
    stages: ['pgy'],
    weight: 2,
    text: '新聞跑馬燈：「五大科招不滿，外科缺額創新高。」下一則是某醫美診所開幕，藝人剪綵。',
    effects: { self: -2 },
    log: '你轉台。轉到哪一台都在講同一件事，只是用不同的語氣。',
  },
];
